### ISSUE TITLE
Invalid directory names

### ISSUE THREAD

**Issue by vraptorche** [danderu/learn-webpack#2]
Due to invalid directory names cannot be checked out on windows

**Comment by delacruz-dev** [comment]
@vraptorche hi! thank you for your feedback. Can you please give me the console error report? I'm not a windows user, but maybe I can do something about it :)

**Comment by mhujer** [comment]
I think the problem is with the colon `:` character, which is not valid for [filenames on Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#file_and_directory_names).

**Comment by delacruz-dev** [comment]
@mhujer ok! now I get it! I've changed the folder names to `_`. Does it work now for you?

**Comment by mhujer** [comment]
@danderu works fine, thanks!
